version: '3.8'
services:
  mysql-database:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=prediction
      - MYSQL_USER=prediction
      - MYSQL_PASSWORD=prediction
      - MYSQL_DATABASE=prediction
