version: '3.8'

services:
  mysql-database:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=prediction
      - MYSQL_USER=prediction
      - MYSQL_PASSWORD=prediction
      - MYSQL_DATABASE=prediction

  web:
    build: .
    command: python main.py
    container_name: app
    restart: unless-stopped
    env_file: .env
    network_mode: "host"
    depends_on:
      - mysql-database

  worker:
    build: .
    command: celery -A parsing.delayed_tasks:celery worker --loglevel info
    container_name: celery
    env_file: .env
    network_mode: "host"
    depends_on:
      - web
      - redis

  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - 6379:6379
